p = int(input("Enter public prime number (p): "))
g = int(input("Enter primitive root (g): "))
a = int(input("Enter Alice's private key: "))
b = int(input("Enter Bob's private key: "))
A = pow(g, a, p)
B = pow(g, b, p)
key_Alice = pow(B, a, p)
key_Bob = pow(A, b, p)
print("\nAlice's public key:", A)
print("Bob's public key:", B)
print("Alice's shared key:", key_Alice)
print("Bob's shared key:", key_Bob)
if key_Alice == key_Bob:
    print("Shared secret key:", key_Alice)
else:
    print("Key exchange failed.")